version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-buster

    working_directory: ~/work

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - deps-fallback

      - run: npm install
      - run: npx rollup --config

      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}
      - run: ./build.sh

      - run: sudo apt-get install -qq -y rsync
      - run:
          name: "Install Hugo"
          command: ls -l hugo || wget -O - https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz | tar zxvf -
      - run: cd v2 && ../hugo
      - run: rsync -rv v2/public/ dist/

      - persist_to_workspace:
          root: ~/work/dist
          paths:
            - ./*
  deploy:
    docker:
      - image: circleci/node:10-buster
    working_directory: ~/work
    steps:
      - attach_workspace:
          at: ~/work/dist
      - run:
          name: "Install pip"
          command: sudo apt-get install -qq -y python-pip libpython-dev git-restore-mtime
      - run: git restore-mtime
      - run:
          name: "Install AWS CLI"
          command: sudo pip install -q awscli --upgrade
      - run: aws s3 sync --acl public-read dist/ s3://8-p.info/
      - run:
          name: Invalidate /*
          command: aws cloudfront create-invalidation --distribution-id E2XRRAO8RPD4HJ --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
